//dummy data
const Products = [
	{
		title: 'iPhone 14',
		category: 'Elektronik',
		seller: 'Cem Balcı',
		sellerVerified: true,
		price: 9999.99,
		stock: 25,
		brand: 'Apple',
	},
	{
		title: 'Galaxy S22',
		category: 'Elektronik',
		seller: 'Cem Balcı',
		sellerVerified: true,
		price: 8499.5,
		stock: 22,
		brand: 'Samsung',
	},
	{
		title: 'Airpods Pro',
		category: 'Elektronik',
		seller: 'Cem Balcı',
		sellerVerified: true,
		price: 2499.0,
		stock: 28,
		brand: 'Apple',
	},
	{
		title: 'ThinkPad X1',
		category: 'Elektronik',
		seller: 'Cem Balcı',
		sellerVerified: true,
		price: 17999.95,
		stock: 24,
		brand: 'Microsoft',
	},
	{
		title: 'OLED TV',
		category: 'Elektronik',
		seller: 'Cem Balcı',
		sellerVerified: true,
		price: 22999.99,
		stock: 27,
		brand: 'Sony',
	},
	{
		title: 'Nike Air Max',
		category: 'Ayakkabı',
		seller: 'Yasemin Güven',
		sellerVerified: false,
		price: 999.5,
		stock: 29,
		brand: 'Nike',
	},
	{
		title: 'Adidas Ultraboost',
		category: 'Ayakkabı',
		seller: 'Yasemin Güven',
		sellerVerified: false,
		price: 1200.0,
		stock: 23,
		brand: 'Adidas',
	},
	{
		title: 'Oyuncu Faresi',
		category: 'Elektronik',
		seller: 'Yasemin Güven',
		sellerVerified: false,
		price: 199.99,
		stock: 26,
		brand: 'Sony',
	},
	{
		title: 'Elektrikli Su Isıtıcı',
		category: 'Beyaz Eşya',
		seller: 'Yasemin Güven',
		sellerVerified: false,
		price: 149.99,
		stock: 21,
		brand: 'Bosch',
	},
	{
		title: 'Blender',
		category: 'Beyaz Eşya',
		seller: 'Yasemin Güven',
		sellerVerified: false,
		price: 549.95,
		stock: 30,
		brand: 'Bosch',
	},
	{
		title: 'Saç Kurutma Makinesi',
		category: 'Kozmetik Ürünler',
		seller: 'Orhan Akkoyun',
		sellerVerified: true,
		price: 199.99,
		stock: 25,
		brand: 'Maybelline',
	},
	{
		title: 'Ruj',
		category: 'Kozmetik Ürünler',
		seller: 'Orhan Akkoyun',
		sellerVerified: true,
		price: 59.95,
		stock: 29,
		brand: 'Maybelline',
	},
	{
		title: 'Defter',
		category: 'Kırtasiye',
		seller: 'Orhan Akkoyun',
		sellerVerified: true,
		price: 15.0,
		stock: 24,
		brand: 'Colgate',
	},
	{
		title: 'Tükenmez Kalemler',
		category: 'Kırtasiye',
		seller: 'Orhan Akkoyun',
		sellerVerified: true,
		price: 7.5,
		stock: 22,
		brand: 'Colgate',
	},
	{
		title: 'Kitaplık',
		category: 'Ev Dekorasyonu',
		seller: 'Fatma Görmez',
		sellerVerified: false,
		price: 899.99,
		stock: 27,
		brand: 'Canon',
	},
	{
		title: 'Yoga Matı',
		category: 'Spor Ekipmanları',
		seller: 'Fatma Görmez',
		sellerVerified: false,
		price: 150.0,
		stock: 28,
		brand: 'Under Armour',
	},
	{
		title: 'Koşu Bandı',
		category: 'Spor Ekipmanları',
		seller: 'Fatma Görmez',
		sellerVerified: false,
		price: 699.99,
		stock: 26,
		brand: 'Bosch',
	},
	{
		title: 'Akustik Gitar',
		category: 'Müzik Aletleri',
		seller: 'Fatma Görmez',
		sellerVerified: false,
		price: 1500.0,
		stock: 23,
		brand: 'Sony',
	},
	{
		title: 'Keman',
		category: 'Müzik Aletleri',
		seller: 'Fatma Görmez',
		sellerVerified: false,
		price: 999.95,
		stock: 30,
		brand: 'Sony',
	},
	{
		title: 'Buzdolabı',
		category: 'Beyaz Eşya',
		seller: 'Ceyda Kurtuluş',
		sellerVerified: true,
		price: 4599.99,
		stock: 25,
		brand: 'Bosch',
	},
	{
		title: 'Çamaşır Makinesi',
		category: 'Beyaz Eşya',
		seller: 'Ceyda Kurtuluş',
		sellerVerified: true,
		price: 4999.95,
		stock: 29,
		brand: 'Bosch',
	},
	{
		title: 'Protein Bar',
		category: 'Yiyecek ve İçecek',
		seller: 'Ceyda Kurtuluş',
		sellerVerified: true,
		price: 99.95,
		stock: 27,
		brand: 'Coca-Cola',
	},
	{
		title: 'Kola Kutusu',
		category: 'Yiyecek ve İçecek',
		seller: 'Ceyda Kurtuluş',
		sellerVerified: true,
		price: 1.5,
		stock: 24,
		brand: 'Coca-Cola',
	},
	{
		title: 'Yazıcı',
		category: 'Ofis Malzemeleri',
		seller: 'Savaş Öztürk',
		sellerVerified: false,
		price: 4999.95,
		stock: 29,
		brand: 'Canon',
	},
	{
		title: 'Projeksiyon Cihazı',
		category: 'Ofis Malzemeleri',
		seller: 'Savaş Öztürk',
		sellerVerified: false,
		price: 2499.99,
		stock: 22,
		brand: 'Canon',
	},
	{
		title: 'Bebek Arabası',
		category: 'Bebek Ürünleri',
		seller: 'Savaş Öztürk',
		sellerVerified: false,
		price: 7499.99,
		stock: 30,
		brand: 'Huawei',
	},
	{
		title: 'Bebek Monitörü',
		category: 'Bebek Ürünleri',
		seller: 'Savaş Öztürk',
		sellerVerified: false,
		price: 199.99,
		stock: 28,
		brand: 'Huawei',
	},
	{
		title: 'Duvar Saati',
		category: 'Ev Dekorasyonu',
		seller: 'Emine Tanrıverdi',
		sellerVerified: true,
		price: 299.99,
		stock: 30,
		brand: 'Colgate',
	},
	{
		title: 'Masa Lambası',
		category: 'Ev Dekorasyonu',
		seller: 'Emine Tanrıverdi',
		sellerVerified: true,
		price: 249.99,
		stock: 25,
		brand: 'Colgate',
	},
	{
		title: 'Tişört',
		category: 'Moda',
		seller: 'Emine Tanrıverdi',
		sellerVerified: true,
		price: 99.99,
		stock: 27,
		brand: 'Nike',
	},
	{
		title: 'Kot Pantolon',
		category: 'Moda',
		seller: 'Emine Tanrıverdi',
		sellerVerified: true,
		price: 149.5,
		stock: 22,
		brand: 'Nike',
	},
	{
		title: 'Küpe',
		category: 'Aksesuarlar',
		seller: 'Can Duru',
		sellerVerified: true,
		price: 59.95,
		stock: 26,
		brand: 'Colgate',
	},
	{
		title: 'Akıllı Saat',
		category: 'Elektronik',
		seller: 'Can Duru',
		sellerVerified: true,
		price: 299.99,
		stock: 30,
		brand: 'Apple',
	},
	{
		title: 'Bluetooth Hoparlör',
		category: 'Elektronik',
		seller: 'Can Duru',
		sellerVerified: true,
		price: 999.95,
		stock: 30,
		brand: 'Sony',
	},
	{
		title: 'Güneş Şapkası',
		category: 'Moda',
		seller: 'Hale Uygur',
		sellerVerified: false,
		price: 39.99,
		stock: 24,
		brand: 'Adidas',
	},
	{
		title: 'Elektrikli Diş Fırçası',
		category: 'Kozmetik Ürünler',
		seller: 'Hale Uygur',
		sellerVerified: false,
		price: 199.99,
		stock: 28,
		brand: 'Colgate',
	},
	{
		title: 'Dijital Kamera',
		category: 'Elektronik',
		seller: 'Hale Uygur',
		sellerVerified: false,
		price: 749.5,
		stock: 25,
		brand: 'Canon',
	},
	{
		title: 'Kamp Çadırı',
		category: 'Spor Ekipmanları',
		seller: 'Hale Uygur',
		sellerVerified: false,
		price: 4999.99,
		stock: 27,
		brand: 'Under Armour',
	},
	{
		title: 'Dizüstü Soğutucu',
		category: 'Ofis Malzemeleri',
		seller: 'Hale Uygur',
		sellerVerified: false,
		price: 799.99,
		stock: 26,
		brand: 'Canon',
	},
	{
		title: 'Akıllı Buzdolabı',
		category: 'Beyaz Eşya',
		seller: 'Hale Uygur',
		sellerVerified: false,
		price: 10499.99,
		stock: 21,
		brand: 'Samsung',
	},
];
export default Products;
